/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RegisterErrors.java
 *
 * Created on Oct 30, 2011, 3:33:51 PM
 */
package edu.ncsu.csc573.project.viewlayer.gui;

/**
 *
 * @author krishna
 */
public class RegisterErrors extends javax.swing.JFrame {

    /** Creates new form RegisterErrors */
    public RegisterErrors() {
        initComponents();
    }
    public void passwordmismatchError() {
        errorMsg.setText("Passwords did not match");
    }
    public void passwordLengthnotMet(){
        errorMsg.setText("Password must contain minimum six characters");
    }
    public void UsernameErrors(){
         errorMsg.setText("Username already exists");
    }
    public void PasswordSucess(){
        errorMsg.setText("Password changed successfully");
        jButton1.setText("Ok");
    }
    public void PasswordFail(){
        errorMsg.setText("Error in changing password");
        jButton1.setText("Try Again");
    }
    public void UpdateSuccess(){
        errorMsg.setText("Updated succesfully");
        jButton1.setText("Ok");
    }
    public void UpdateFail(){
        errorMsg.setText("Failed to update the configuration file. Enter vaild directory");
        jButton1.setText("Ok");
    }
    //public void username errors based on response
    public void FirstnameError(){
        errorMsg.setText("First Name not entered");
        jButton1.setText("Try Again");
    }
     public void LastnameError(){
        errorMsg.setText("Last Name not entered");
        jButton1.setText("Try Again");
    }
     public void UsernameError(){
        errorMsg.setText("User Name not entered");
        jButton1.setText("Try Again");
    }
      public void EmailError(){
        errorMsg.setText("First Name not entered");
        jButton1.setText("Try Again");
    }
      public void UserError(){
        errorMsg.setText("Username already exists");
        jButton1.setText("Try Again");  
      }
       public void ServerError(){
        errorMsg.setText("Server not reachable");
        jButton1.setText("Try Again");  
      }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        errorMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(500, 350, 0, 0));
        setResizable(false);

        jButton1.setText("Try Again");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        errorMsg.setText("error");
        errorMsg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(errorMsg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(jButton1)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(errorMsg)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.setVisible(false);
    // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterErrors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterErrors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterErrors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterErrors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new RegisterErrors().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorMsg;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
