/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchResults.java
 *
 * Created on Oct 26, 2011, 2:05:10 AM
 */
package edu.ncsu.csc573.project.viewlayer.gui;

import edu.ncsu.csc573.project.common.messages.EnumParamsType;
import edu.ncsu.csc573.project.common.messages.PublishSearchParameter;
import java.util.Locale;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author krishna
 */
public class SearchResults extends javax.swing.JFrame {
    
    private PublishSearchParameter searchResults;
    private static final int RESULTS_PER_PAGE = 5;
//    Result[] res = new Result[5];
    
    /** Creates new form SearchResults */
    public SearchResults() {
        initComponents();
        ShowResults();
   }
    
    public SearchResults(PublishSearchParameter searchResults) {
        this.searchResults = searchResults;
        this.searchResults.resetCounter();
      
       initComponents();
       ShowResults();
    }
    
    public void ShowResults() {
        int r = 0;
        //BoxLayout bx = new BoxLayout(this, BoxLayout.Y_AXIS);
        while (searchResults.getParamCount() < searchResults.getSize() && r < 5) {
            fname.setText(searchResults.getParamValue(EnumParamsType.FILENAME).toString());
            abs.setText(searchResults.getParamValue(EnumParamsType.ABSTRACT).toString());
            IPAdd.setText(searchResults.getParamValue(EnumParamsType.IPADDRESS).toString());
            //Row absRow = new Row("Abstract", searchResults.getParamValue(EnumParamsType.ABSTRACT).toString());
            //Row down = new Row("IP", searchResults.getParamValue(EnumParamsType.IPADDRESS).toString(), true);
           // System.out.println(" r value is " + r);
            //res[r] = new Result(fileRow, absRow, down);            
            //Row.add(res[r]);           
            r++;
            searchResults.setNextParam();
            
       }
        revalidate();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        List = new javax.swing.JPanel();
        Row = new javax.swing.JPanel();
        fname = new javax.swing.JLabel();
        abs = new javax.swing.JLabel();
        IPAdd = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Search");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Search Results");

        jButton8.setText("Previous");

        jButton9.setText("Next");

        fname.setText("Filename");

        abs.setText("Abstract");

        IPAdd.setText("IP Address");

        javax.swing.GroupLayout RowLayout = new javax.swing.GroupLayout(Row);
        Row.setLayout(RowLayout);
        RowLayout.setHorizontalGroup(
            RowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fname)
                    .addComponent(abs)
                    .addComponent(IPAdd))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        RowLayout.setVerticalGroup(
            RowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(abs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IPAdd)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ListLayout = new javax.swing.GroupLayout(List);
        List.setLayout(ListLayout);
        ListLayout.setHorizontalGroup(
            ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Row, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        ListLayout.setVerticalGroup(
            ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Row, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jButton8)
                        .addGap(59, 59, 59)
                        .addComponent(jButton9)))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton8, jButton9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(List, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton8))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void linkButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkButton3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_linkButton3ActionPerformed
    
private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchResults.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            @Override
            public void run() {
                new SearchResults().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IPAdd;
    private javax.swing.JPanel List;
    private javax.swing.JPanel Row;
    private javax.swing.JLabel abs;
    private javax.swing.JLabel fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}


/*
class Result extends JPanel {
    
    private Row attributes[];
    
    public Result(Row name, Row abs, Row IP) {
        attributes = new Row[3];
        attributes[0] = name;
        attributes[1] = abs;
        attributes[2] = IP;
        
        setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
        
        add(attributes[0]);
        add(attributes[1]);
        add(attributes[2]);
        setVisible(true);
    }
}

class Row extends JPanel {
    
    private JLabel field;
    private JLabel value;
    private JButton download;
    
    public Row(String fieldName, String valueName) {
        field = new JLabel();
        field.setText(fieldName);
        value = new JLabel();
        value.setText(valueName);
        setLayout(new BoxLayout(this, BoxLayout.X_AXIS));
        add(field);
        add(value);
        setVisible(true);
    }
    
    public Row(String fieldName, String valueName, boolean isButtonPresent) {
        field = new JLabel();
        field.setText(fieldName);
        value = new JLabel();
        value.setText(valueName);
        download = new JButton("Download");
        setLayout(new BoxLayout(this, BoxLayout.X_AXIS));
        add(field);
        add(value);
        add(download);
        setVisible(true);
    }
 * }
 * 
 */


