/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingsFrame.java
 *
 * Created on Oct 30, 2011, 7:37:41 PM
 */
package edu.ncsu.csc573.project.viewlayer.gui;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author krishna
 */
public class SettingsFrame extends javax.swing.JFrame {

    /** Creates new form SettingsFrame */
    public SettingsFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        filechoosetext = new javax.swing.JTextField();
        filechoosebutton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        oldpwd = new javax.swing.JLabel();
        newpwd = new javax.swing.JLabel();
        confnewpwd = new javax.swing.JLabel();
        changepwd = new javax.swing.JButton();
        oldpasswd = new javax.swing.JPasswordField();
        newpasswd = new javax.swing.JPasswordField();
        confnewpasswd = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 250, 0, 0));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Settings");

        jLabel2.setText("Change the folder to share");

        filechoosetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filechoosetextActionPerformed(evt);
            }
        });

        filechoosebutton.setText("Browse");
        filechoosebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filechoosebuttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Change Password");

        oldpwd.setText("Old Password");

        newpwd.setText("New Password");

        confnewpwd.setText("Confirm New Password");

        changepwd.setText("Change Password");
        changepwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepwdActionPerformed(evt);
            }
        });

        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oldpwd)
                            .addComponent(newpwd)
                            .addComponent(confnewpwd)
                            .addComponent(changepwd))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(back)
                            .addComponent(newpasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oldpasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(confnewpasswd, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(filechoosebutton)
                            .addComponent(filechoosetext, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {confnewpwd, newpwd, oldpwd});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {confnewpasswd, newpasswd, oldpasswd});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {back, filechoosebutton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(filechoosetext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filechoosebutton)
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldpwd)
                    .addComponent(oldpasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpwd)
                    .addComponent(newpasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confnewpwd)
                    .addComponent(confnewpasswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changepwd)
                    .addComponent(back))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {back, changepwd});

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void changepwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepwdActionPerformed
// TODO add your handling code here:
  String pwd = newpasswd.getText();
  String confpwd = confnewpasswd.getText();
  int compare = pwd.compareTo(confpwd);
  int length = pwd.length(); 
   if (compare !=0)
   {
        PasswdMismatchErrors();
   }
   else if (length < 6)
   {
         PasswdLengthErrors();
   }
   //Communication handler instance
   else {
      //Comm layer instance
            PasswdChangeSuccess();
      }
    //Comm instance to change password
}//GEN-LAST:event_changepwdActionPerformed

public void fileChooser() {
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Select Folder");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
        filechoosetext.setText(chooser.getName(chooser.getSelectedFile()));
    } 
    }

private void filechoosetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filechoosetextActionPerformed
// TODO add your handling code here:
    
}//GEN-LAST:event_filechoosetextActionPerformed

private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
    Search newSearch = new Search();
    newSearch.setVisible(true);
}//GEN-LAST:event_backActionPerformed

private void filechoosebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filechoosebuttonActionPerformed
    fileChooser();
    filechoosebutton.setText("Updating");
    //call an instance
    UpdateDoneSuccess();
    
}//GEN-LAST:event_filechoosebuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SettingsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new SettingsFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton changepwd;
    private javax.swing.JPasswordField confnewpasswd;
    private javax.swing.JLabel confnewpwd;
    private javax.swing.JButton filechoosebutton;
    private javax.swing.JTextField filechoosetext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField newpasswd;
    private javax.swing.JLabel newpwd;
    private javax.swing.JPasswordField oldpasswd;
    private javax.swing.JLabel oldpwd;
    // End of variables declaration//GEN-END:variables

    private void PasswdMismatchErrors() {
        RegisterErrors passwdRegisterErrors = new RegisterErrors();
        passwdRegisterErrors.passwordmismatchError();
        passwdRegisterErrors.setVisible(true);
    }
        private void PasswdLengthErrors() {
        RegisterErrors passwdRegisterErrors = new RegisterErrors();
        passwdRegisterErrors.passwordLengthnotMet();
        passwdRegisterErrors.setVisible(true);
    }

    private void PasswdChangeSuccess() {
        RegisterErrors passwdRegisterSuccess = new RegisterErrors();
        passwdRegisterSuccess.PasswordSucess();
        passwdRegisterSuccess.setVisible(true);
    }
     private void UpdateDoneSuccess() {
        RegisterErrors update = new RegisterErrors();
        update.UpdateSuccess();
        update.setVisible(true);
    }
}