/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Unpublish.java
 *
 * Created on Dec 6, 2011, 1:33:58 AM
 */
package edu.ncsu.csc573.project.viewlayer.gui;

import edu.ncsu.csc573.project.commlayer.CommunicationServiceFactory;
import edu.ncsu.csc573.project.common.ConfigurationManager;
import edu.ncsu.csc573.project.common.messages.EnumOperationType;
import edu.ncsu.csc573.project.common.messages.EnumParamsType;
import edu.ncsu.csc573.project.common.messages.IParameter;
import edu.ncsu.csc573.project.common.messages.IResponse;
import edu.ncsu.csc573.project.common.messages.Parameter;
import edu.ncsu.csc573.project.common.messages.UnPublishRequestMessage;
import edu.ncsu.csc573.project.controllayer.hashspacemanagement.DigestAdaptor;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author krishna
 */
public class Unpublish extends javax.swing.JFrame {

    /** Creates new form Unpublish */
    public Unpublish() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inputtext = new javax.swing.JTextField();
        unpublishbutton = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Select File to unpublish");

        unpublishbutton.setText("Browse");
        unpublishbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unpublishbuttonActionPerformed(evt);
            }
        });

        Back.setText("Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Back)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputtext, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(unpublishbutton)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Back, unpublishbutton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unpublishbutton))
                .addGap(18, 18, 18)
                .addComponent(Back)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void unpublishbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unpublishbuttonActionPerformed

    // TODO add your handling code here:
    JFileChooser chooser = fileChooser();
   if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
       inputtext.setText(chooser.getSelectedFile().getAbsolutePath());
    } 
    try {
        UnPublishRequestMessage req = new UnPublishRequestMessage();
        IParameter param = new Parameter();
        param.add(EnumParamsType.FILENAME, new File(inputtext.getText()).getName());
        param.add(EnumParamsType.FILEDIGEST, DigestAdaptor.getInstance().getDigest(new File(inputtext.getText())));
        req.createRequest(EnumOperationType.UNPUBLISH, param);
        IResponse res = CommunicationServiceFactory.getInstance().executeRequest(req);
        UnpublishSuccess();
    } catch (Exception e) {
        Unpublishfail();
    } 
}//GEN-LAST:event_unpublishbuttonActionPerformed

private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
// TODO add your handling code here:
    this.setVisible(false);
}//GEN-LAST:event_BackActionPerformed

public JFileChooser fileChooser() {
        JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Select File to unpublish");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setAcceptAllFileFilterUsed(false);
        return chooser;
    }

   private void Unpublishfail() {
        RegisterErrors update = new RegisterErrors();
        update.Unpublishfailed();
        update.setVisible(true);
    }
   
   private void UnpublishSuccess() {
        RegisterErrors update = new RegisterErrors();
        update.Unpublishsuccess();
        update.setVisible(true);
    }
   
   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Unpublish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Unpublish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Unpublish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Unpublish.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Unpublish().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField inputtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton unpublishbutton;
    // End of variables declaration//GEN-END:variables
}
