//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.06 at 01:33:25 AM EST 
//


package edu.ncsu.csc573.project.common.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatchMetricFileParamType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatchMetricFileParamType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.doogle.project.csc573.csc.ncsu.edu}FileParamType">
 *       &lt;sequence>
 *         &lt;element name="MatchMetric" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatchMetricFileParamType", propOrder = {
    "matchMetric"
})
public class MatchMetricFileParamType
    extends FileParamType
{

    @XmlElement(name = "MatchMetric")
    protected double matchMetric;

    /**
     * Gets the value of the matchMetric property.
     * 
     */
    public double getMatchMetric() {
        return matchMetric;
    }

    /**
     * Sets the value of the matchMetric property.
     * 
     */
    public void setMatchMetric(double value) {
        this.matchMetric = value;
    }

}
