//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.29 at 02:04:44 PM EDT 
//


package edu.ncsu.csc573.project.common.schema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the edu.ncsu.csc573.project.common.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: edu.ncsu.csc573.project.common.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RegisterType }
     * 
     */
    public RegisterType createRegisterType() {
        return new RegisterType();
    }

    /**
     * Create an instance of {@link SearchTypeParams }
     * 
     */
    public SearchTypeParams createSearchTypeParams() {
        return new SearchTypeParams();
    }

    /**
     * Create an instance of {@link ForgotPasswdType }
     * 
     */
    public ForgotPasswdType createForgotPasswdType() {
        return new ForgotPasswdType();
    }

    /**
     * Create an instance of {@link LogoutParamsType }
     * 
     */
    public LogoutParamsType createLogoutParamsType() {
        return new LogoutParamsType();
    }

    /**
     * Create an instance of {@link RegisterParamsType }
     * 
     */
    public RegisterParamsType createRegisterParamsType() {
        return new RegisterParamsType();
    }

    /**
     * Create an instance of {@link LoginParamsType }
     * 
     */
    public LoginParamsType createLoginParamsType() {
        return new LoginParamsType();
    }

    /**
     * Create an instance of {@link LogoutType }
     * 
     */
    public LogoutType createLogoutType() {
        return new LogoutType();
    }

    /**
     * Create an instance of {@link SearchType }
     * 
     */
    public SearchType createSearchType() {
        return new SearchType();
    }

    /**
     * Create an instance of {@link CommandType }
     * 
     */
    public CommandType createCommandType() {
        return new CommandType();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link LoginType }
     * 
     */
    public LoginType createLoginType() {
        return new LoginType();
    }

    /**
     * Create an instance of {@link ForgotPWDType }
     * 
     */
    public ForgotPWDType createForgotPWDType() {
        return new ForgotPWDType();
    }

}
