//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.21 at 02:54:48 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.doogle.project.csc573.csc.ncsu.edu", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package edu.ncsu.csc573.project.common.schema;
