//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.10.25 at 06:58:08 PM EDT 
//


package edu.ncsu.csc573.project.common.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegisterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RegisterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parmas" type="{http://www.doogle.project.csc573.csc.ncsu.edu}RegisterParamsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RegisterType", propOrder = {
    "parmas"
})
public class RegisterType {

    @XmlElement(required = true)
    protected RegisterParamsType parmas;

    /**
     * Gets the value of the parmas property.
     * 
     * @return
     *     possible object is
     *     {@link RegisterParamsType }
     *     
     */
    public RegisterParamsType getParmas() {
        return parmas;
    }

    /**
     * Sets the value of the parmas property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegisterParamsType }
     *     
     */
    public void setParmas(RegisterParamsType value) {
        this.parmas = value;
    }

}
